FORMAT: 1A
HOST: https://iot-sprinkler-switch.herokuapp.com/webapi/

# sprinkler-switch

This API is for checking and changing status of a sprinkler in a specific house.

# Ping [/ping]

## Ping service [GET]

Returns `200` if service is alive.

+ Response 200 (application/json)


## Sprinkler status [/houses/{house_id}]
Get or change status of a sprinkler 

+ Parameters
    + house_id (required, string, `1234`) ... unique ID of the House.


### Get Sprinkler Status [GET]
You can get current status of a sprinkler.

`seconds_left` integer time after which sprinkler will automatically turn off <br>

`200` response code means switch is currently on. <br>
`204` means switch with `houseId` does not exist. <br>
`404` means switch is currently turned off. <br>

+ Response 200 (application/json)

        {
            "seconds_left": 45
        }
        
+ Response 204 (application/json)

+ Response 404 (application/json)
        

### Turn The Sprinkler On [PUT]

You can switch sprinkler on using this action. It takes an optional JSON
object containing one argument - `timeout` meaning how long sprinkler will stay on.
If no JSON object is passed timeout will be set to default time. <br>
If sprinkler did turn on `200` will be returned.

`timeout` it is an optional argument **default value - 60 seconds**<br>
It must be positive integer. It indicates for how long sprinkler must stay on <br>
if sprinkler is already on, then it will just change timeout to a new value. 

+ Request (application/json)

        {
            "timeout": 30
        }

+ Response 200 (application/json)

+ Response 204 (application/json)

### Turn The Sprinkler Off [DELETE]
You can turn the sprinkler off any time using this action. <br>
`200` - response code means sprinkler was successfully turned off or it was already off. <br>
`204` means switch with `houseId` was not found.

+ Request (application/json)

+ Response 200 (application/json)

+ Response 204 (application/json)