FORMAT: 1A
HOST: https://iot-sprinkler-switch.herokuapp.com/webapi/

# sprinkler-switch

This API is for checking and changing status of a sprinkler in a specific house.

# Ping [/ping]

## Ping service [GET]

Returns `200` if service is alive.

+ Response 200 (application/json)


## Sprinkler status [/houses/{house_id}]
Get or change status of a sprinkler 

+ Parameters
    + house_id (required, string, `d28f9e91-ea20-43cf-abf5-24f3d659afef`) ... unique ID of the House.


### Get Sprinkler Status [GET]
You can get current status of a sprinkler.
`house_id` same string which was passed in URI. <br>
`status` values can be `"on"` or `"off"` indicating sprinkler state. <br>
`seconds_left` integer time after which sprinkler will automatically turn off <br>

+ Response 200 (application/json)

        {
            "house_id": "d28f9e91-ea20-43cf-abf5-24f3d659afef",
            "status": "on",
            "seconds_left": 45
        }
        
+ Response 200 (application/json)

        {
            "house_id": "d28f9e91-ea20-43cf-abf5-24f3d659afef",
            "status": "off"
        }
        

### Change Sprinkler Status [PUT]

You may switch sprinkler on or off using this action. It takes a JSON
object containing order and optional argument - number of seconds. 
If order is "on" you can also say for how long sprinkler must be on 
with optional "timeout" key.
After posting action, if the order was executed server will return code **200** 
else http response code explaining error.

`set_status` values are `"on"` or `"off"` indicating desire to turn sprinkler on or off.<br>
`timeout` it is an optional argument **default value - 60 seconds**<br>
It must be positive integer. It indicates for how long sprinkler must stay on <br>
if sprinkler is already on, then it will just change timeout to a new value. 

+ Request (application/json)

        {
            "set_status": "on",
            "timeout": 30
        }
        
+ Request (application/json)

        {
            "set_status": "on"
        }
        
+ Request (application/json)

        {
            "set_status": "off"
        }

+ Response 200 (application/json)
  
        {
            "house_id": "d28f9e91-ea20-43cf-abf5-24f3d659afef",
            "status": "on",
            "seconds_left": 60
        }